export const TRENDING_START     = 'TRENDING_START';
export const TRENDING_SUCCESS   = 'TRENDING_SUCCESS';
export const TRENDING_FAIL      = 'TRENDING_FAIL';
export const TRENDING_LANG_SET  = 'TRENDING_LANG_SET';
export const TRENDING_SINCE_SET = 'TRENDING_SINCE_SET';
export const TRENDING_TYPE_SET  = 'TRENDING_TYPE_SET';



export const POPULAR_START      = 'POPULAR_START';
export const POPULAR_SUCCESS    = 'POPULAR_SUCCESS';
export const POPULAR_FAIL       = 'POPULAR_FAIL';
export const POPULAR_LANG_SET   = 'POPULAR_LANG_SET';
export const POPULAR_PAGE_SET   = 'POPULAR_PAGE_SET';

